// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package machine

import (
	"context"
	"errors"
	"fmt"
	"github.com/ServiceWeaver/weaver"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:  "TCC-UNISINOS/components/machine/MachineComponent",
		Iface: reflect.TypeOf((*MachineComponent)(nil)).Elem(),
		Impl:  reflect.TypeOf(machineComponent{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return machineComponent_local_stub{impl: impl.(MachineComponent), tracer: tracer, addMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "TCC-UNISINOS/components/machine/MachineComponent", Method: "Add", Remote: false, Generated: true}), calculateOEEMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "TCC-UNISINOS/components/machine/MachineComponent", Method: "CalculateOEE", Remote: false, Generated: true}), getMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "TCC-UNISINOS/components/machine/MachineComponent", Method: "Get", Remote: false, Generated: true}), getByMachineIDMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "TCC-UNISINOS/components/machine/MachineComponent", Method: "GetByMachineID", Remote: false, Generated: true}), updateMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "TCC-UNISINOS/components/machine/MachineComponent", Method: "Update", Remote: false, Generated: true})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return machineComponent_client_stub{stub: stub, addMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "TCC-UNISINOS/components/machine/MachineComponent", Method: "Add", Remote: true, Generated: true}), calculateOEEMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "TCC-UNISINOS/components/machine/MachineComponent", Method: "CalculateOEE", Remote: true, Generated: true}), getMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "TCC-UNISINOS/components/machine/MachineComponent", Method: "Get", Remote: true, Generated: true}), getByMachineIDMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "TCC-UNISINOS/components/machine/MachineComponent", Method: "GetByMachineID", Remote: true, Generated: true}), updateMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "TCC-UNISINOS/components/machine/MachineComponent", Method: "Update", Remote: true, Generated: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return machineComponent_server_stub{impl: impl.(MachineComponent), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return machineComponent_reflect_stub{caller: caller}
		},
		RefData: "⟦03b2ebc7:wEaVeReDgE:TCC-UNISINOS/components/machine/MachineComponent→TCC-UNISINOS/components/productionCycle/ProductionCycleComponent⟧\n⟦7f7b8483:wEaVeReDgE:TCC-UNISINOS/components/machine/MachineComponent→TCC-UNISINOS/components/oee/OEEComponent⟧\n",
	})
}

// weaver.InstanceOf checks.
var _ weaver.InstanceOf[MachineComponent] = (*machineComponent)(nil)

// weaver.Router checks.
var _ weaver.Unrouted = (*machineComponent)(nil)

// Local stub implementations.

type machineComponent_local_stub struct {
	impl                  MachineComponent
	tracer                trace.Tracer
	addMetrics            *codegen.MethodMetrics
	calculateOEEMetrics   *codegen.MethodMetrics
	getMetrics            *codegen.MethodMetrics
	getByMachineIDMetrics *codegen.MethodMetrics
	updateMetrics         *codegen.MethodMetrics
}

// Check that machineComponent_local_stub implements the MachineComponent interface.
var _ MachineComponent = (*machineComponent_local_stub)(nil)

func (s machineComponent_local_stub) Add(ctx context.Context, a0 Machine) (err error) {
	// Update metrics.
	begin := s.addMetrics.Begin()
	defer func() { s.addMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "machine.MachineComponent.Add", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Add(ctx, a0)
}

func (s machineComponent_local_stub) CalculateOEE(ctx context.Context, a0 int) (r0 float64, err error) {
	// Update metrics.
	begin := s.calculateOEEMetrics.Begin()
	defer func() { s.calculateOEEMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "machine.MachineComponent.CalculateOEE", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.CalculateOEE(ctx, a0)
}

func (s machineComponent_local_stub) Get(ctx context.Context) (r0 []Machine, err error) {
	// Update metrics.
	begin := s.getMetrics.Begin()
	defer func() { s.getMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "machine.MachineComponent.Get", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Get(ctx)
}

func (s machineComponent_local_stub) GetByMachineID(ctx context.Context, a0 int) (r0 Machine, err error) {
	// Update metrics.
	begin := s.getByMachineIDMetrics.Begin()
	defer func() { s.getByMachineIDMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "machine.MachineComponent.GetByMachineID", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetByMachineID(ctx, a0)
}

func (s machineComponent_local_stub) Update(ctx context.Context, a0 int, a1 Machine) (r0 Machine, err error) {
	// Update metrics.
	begin := s.updateMetrics.Begin()
	defer func() { s.updateMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "machine.MachineComponent.Update", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Update(ctx, a0, a1)
}

// Client stub implementations.

type machineComponent_client_stub struct {
	stub                  codegen.Stub
	addMetrics            *codegen.MethodMetrics
	calculateOEEMetrics   *codegen.MethodMetrics
	getMetrics            *codegen.MethodMetrics
	getByMachineIDMetrics *codegen.MethodMetrics
	updateMetrics         *codegen.MethodMetrics
}

// Check that machineComponent_client_stub implements the MachineComponent interface.
var _ MachineComponent = (*machineComponent_client_stub)(nil)

func (s machineComponent_client_stub) Add(ctx context.Context, a0 Machine) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.addMetrics.Begin()
	defer func() { s.addMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "machine.MachineComponent.Add", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += serviceweaver_size_Machine_5724f675(&a0)
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	(a0).WeaverMarshal(enc)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

func (s machineComponent_client_stub) CalculateOEE(ctx context.Context, a0 int) (r0 float64, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.calculateOEEMetrics.Begin()
	defer func() { s.calculateOEEMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "machine.MachineComponent.CalculateOEE", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += 8
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.Int(a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 1, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = dec.Float64()
	err = dec.Error()
	return
}

func (s machineComponent_client_stub) Get(ctx context.Context) (r0 []Machine, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getMetrics.Begin()
	defer func() { s.getMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "machine.MachineComponent.Get", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	var shardKey uint64

	// Call the remote method.
	var results []byte
	results, err = s.stub.Run(ctx, 2, nil, shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_slice_Machine_6fd3dd11(dec)
	err = dec.Error()
	return
}

func (s machineComponent_client_stub) GetByMachineID(ctx context.Context, a0 int) (r0 Machine, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getByMachineIDMetrics.Begin()
	defer func() { s.getByMachineIDMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "machine.MachineComponent.GetByMachineID", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += 8
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.Int(a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 3, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	(&r0).WeaverUnmarshal(dec)
	err = dec.Error()
	return
}

func (s machineComponent_client_stub) Update(ctx context.Context, a0 int, a1 Machine) (r0 Machine, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.updateMetrics.Begin()
	defer func() { s.updateMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "machine.MachineComponent.Update", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += 8
	size += serviceweaver_size_Machine_5724f675(&a1)
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.Int(a0)
	(a1).WeaverMarshal(enc)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 4, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	(&r0).WeaverUnmarshal(dec)
	err = dec.Error()
	return
}

// Note that "weaver generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][24]struct{}](`

ERROR: You generated this file with 'weaver generate' v0.24.6 (codegen
version v0.24.0). The generated code is incompatible with the version of the
github.com/ServiceWeaver/weaver module that you're using. The weaver module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/ServiceWeaver/weaver

We recommend updating the weaver module and the 'weaver generate' command by
running the following.

    go get github.com/ServiceWeaver/weaver@latest
    go install github.com/ServiceWeaver/weaver/cmd/weaver@latest

Then, re-run 'weaver generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/ServiceWeaver/weaver/issues.

`)

// Server stub implementations.

type machineComponent_server_stub struct {
	impl    MachineComponent
	addLoad func(key uint64, load float64)
}

// Check that machineComponent_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*machineComponent_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s machineComponent_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "Add":
		return s.add
	case "CalculateOEE":
		return s.calculateOEE
	case "Get":
		return s.get
	case "GetByMachineID":
		return s.getByMachineID
	case "Update":
		return s.update
	default:
		return nil
	}
}

func (s machineComponent_server_stub) add(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 Machine
	(&a0).WeaverUnmarshal(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.Add(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s machineComponent_server_stub) calculateOEE(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 int
	a0 = dec.Int()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.CalculateOEE(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Float64(r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s machineComponent_server_stub) get(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.Get(ctx)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_slice_Machine_6fd3dd11(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s machineComponent_server_stub) getByMachineID(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 int
	a0 = dec.Int()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetByMachineID(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	(r0).WeaverMarshal(enc)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s machineComponent_server_stub) update(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 int
	a0 = dec.Int()
	var a1 Machine
	(&a1).WeaverUnmarshal(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.Update(ctx, a0, a1)

	// Encode the results.
	enc := codegen.NewEncoder()
	(r0).WeaverMarshal(enc)
	enc.Error(appErr)
	return enc.Data(), nil
}

// Reflect stub implementations.

type machineComponent_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that machineComponent_reflect_stub implements the MachineComponent interface.
var _ MachineComponent = (*machineComponent_reflect_stub)(nil)

func (s machineComponent_reflect_stub) Add(ctx context.Context, a0 Machine) (err error) {
	err = s.caller("Add", ctx, []any{a0}, []any{})
	return
}

func (s machineComponent_reflect_stub) CalculateOEE(ctx context.Context, a0 int) (r0 float64, err error) {
	err = s.caller("CalculateOEE", ctx, []any{a0}, []any{&r0})
	return
}

func (s machineComponent_reflect_stub) Get(ctx context.Context) (r0 []Machine, err error) {
	err = s.caller("Get", ctx, []any{}, []any{&r0})
	return
}

func (s machineComponent_reflect_stub) GetByMachineID(ctx context.Context, a0 int) (r0 Machine, err error) {
	err = s.caller("GetByMachineID", ctx, []any{a0}, []any{&r0})
	return
}

func (s machineComponent_reflect_stub) Update(ctx context.Context, a0 int, a1 Machine) (r0 Machine, err error) {
	err = s.caller("Update", ctx, []any{a0, a1}, []any{&r0})
	return
}

// AutoMarshal implementations.

var _ codegen.AutoMarshal = (*Machine)(nil)

type __is_Machine[T ~struct {
	MachineID     int     "json:\"machineID\""
	Name          string  "json:\"name\""
	AvailableTime float64 "json:\"availableTime\""
	weaver.AutoMarshal
}] struct{}

var _ __is_Machine[Machine]

func (x *Machine) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Machine.WeaverMarshal: nil receiver"))
	}
	enc.Int(x.MachineID)
	enc.String(x.Name)
	enc.Float64(x.AvailableTime)
}

func (x *Machine) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Machine.WeaverUnmarshal: nil receiver"))
	}
	x.MachineID = dec.Int()
	x.Name = dec.String()
	x.AvailableTime = dec.Float64()
}

// Encoding/decoding implementations.

func serviceweaver_enc_slice_Machine_6fd3dd11(enc *codegen.Encoder, arg []Machine) {
	if arg == nil {
		enc.Len(-1)
		return
	}
	enc.Len(len(arg))
	for i := 0; i < len(arg); i++ {
		(arg[i]).WeaverMarshal(enc)
	}
}

func serviceweaver_dec_slice_Machine_6fd3dd11(dec *codegen.Decoder) []Machine {
	n := dec.Len()
	if n == -1 {
		return nil
	}
	res := make([]Machine, n)
	for i := 0; i < n; i++ {
		(&res[i]).WeaverUnmarshal(dec)
	}
	return res
}

// Size implementations.

// serviceweaver_size_Machine_5724f675 returns the size (in bytes) of the serialization
// of the provided type.
func serviceweaver_size_Machine_5724f675(x *Machine) int {
	size := 0
	size += 8
	size += (4 + len(x.Name))
	size += 8
	size += 0
	return size
}
