// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package productioncycle

import (
	"context"
	"errors"
	"fmt"
	"github.com/ServiceWeaver/weaver"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
	"time"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:  "TCC-UNISINOS/components/productionCycle/ProductionCycleComponent",
		Iface: reflect.TypeOf((*ProductionCycleComponent)(nil)).Elem(),
		Impl:  reflect.TypeOf(ProductionCycleComponentStruct{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return productionCycleComponent_local_stub{impl: impl.(ProductionCycleComponent), tracer: tracer, addMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "TCC-UNISINOS/components/productionCycle/ProductionCycleComponent", Method: "Add", Remote: false, Generated: true}), getMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "TCC-UNISINOS/components/productionCycle/ProductionCycleComponent", Method: "Get", Remote: false, Generated: true}), getByMachineIDMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "TCC-UNISINOS/components/productionCycle/ProductionCycleComponent", Method: "GetByMachineID", Remote: false, Generated: true}), getFirstCycleByMachineIDMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "TCC-UNISINOS/components/productionCycle/ProductionCycleComponent", Method: "GetFirstCycleByMachineID", Remote: false, Generated: true})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return productionCycleComponent_client_stub{stub: stub, addMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "TCC-UNISINOS/components/productionCycle/ProductionCycleComponent", Method: "Add", Remote: true, Generated: true}), getMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "TCC-UNISINOS/components/productionCycle/ProductionCycleComponent", Method: "Get", Remote: true, Generated: true}), getByMachineIDMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "TCC-UNISINOS/components/productionCycle/ProductionCycleComponent", Method: "GetByMachineID", Remote: true, Generated: true}), getFirstCycleByMachineIDMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "TCC-UNISINOS/components/productionCycle/ProductionCycleComponent", Method: "GetFirstCycleByMachineID", Remote: true, Generated: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return productionCycleComponent_server_stub{impl: impl.(ProductionCycleComponent), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return productionCycleComponent_reflect_stub{caller: caller}
		},
		RefData: "",
	})
}

// weaver.InstanceOf checks.
var _ weaver.InstanceOf[ProductionCycleComponent] = (*ProductionCycleComponentStruct)(nil)

// weaver.Router checks.
var _ weaver.Unrouted = (*ProductionCycleComponentStruct)(nil)

// Local stub implementations.

type productionCycleComponent_local_stub struct {
	impl                            ProductionCycleComponent
	tracer                          trace.Tracer
	addMetrics                      *codegen.MethodMetrics
	getMetrics                      *codegen.MethodMetrics
	getByMachineIDMetrics           *codegen.MethodMetrics
	getFirstCycleByMachineIDMetrics *codegen.MethodMetrics
}

// Check that productionCycleComponent_local_stub implements the ProductionCycleComponent interface.
var _ ProductionCycleComponent = (*productionCycleComponent_local_stub)(nil)

func (s productionCycleComponent_local_stub) Add(ctx context.Context, a0 ProductionCycle) (err error) {
	// Update metrics.
	begin := s.addMetrics.Begin()
	defer func() { s.addMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "productioncycle.ProductionCycleComponent.Add", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Add(ctx, a0)
}

func (s productionCycleComponent_local_stub) Get(ctx context.Context) (r0 []ProductionCycle, err error) {
	// Update metrics.
	begin := s.getMetrics.Begin()
	defer func() { s.getMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "productioncycle.ProductionCycleComponent.Get", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Get(ctx)
}

func (s productionCycleComponent_local_stub) GetByMachineID(ctx context.Context, a0 int) (r0 []ProductionCycle, err error) {
	// Update metrics.
	begin := s.getByMachineIDMetrics.Begin()
	defer func() { s.getByMachineIDMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "productioncycle.ProductionCycleComponent.GetByMachineID", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetByMachineID(ctx, a0)
}

func (s productionCycleComponent_local_stub) GetFirstCycleByMachineID(ctx context.Context, a0 int) (r0 ProductionCycle, err error) {
	// Update metrics.
	begin := s.getFirstCycleByMachineIDMetrics.Begin()
	defer func() { s.getFirstCycleByMachineIDMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "productioncycle.ProductionCycleComponent.GetFirstCycleByMachineID", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetFirstCycleByMachineID(ctx, a0)
}

// Client stub implementations.

type productionCycleComponent_client_stub struct {
	stub                            codegen.Stub
	addMetrics                      *codegen.MethodMetrics
	getMetrics                      *codegen.MethodMetrics
	getByMachineIDMetrics           *codegen.MethodMetrics
	getFirstCycleByMachineIDMetrics *codegen.MethodMetrics
}

// Check that productionCycleComponent_client_stub implements the ProductionCycleComponent interface.
var _ ProductionCycleComponent = (*productionCycleComponent_client_stub)(nil)

func (s productionCycleComponent_client_stub) Add(ctx context.Context, a0 ProductionCycle) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.addMetrics.Begin()
	defer func() { s.addMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "productioncycle.ProductionCycleComponent.Add", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	(a0).WeaverMarshal(enc)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

func (s productionCycleComponent_client_stub) Get(ctx context.Context) (r0 []ProductionCycle, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getMetrics.Begin()
	defer func() { s.getMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "productioncycle.ProductionCycleComponent.Get", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	var shardKey uint64

	// Call the remote method.
	var results []byte
	results, err = s.stub.Run(ctx, 1, nil, shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_slice_ProductionCycle_ba3c321f(dec)
	err = dec.Error()
	return
}

func (s productionCycleComponent_client_stub) GetByMachineID(ctx context.Context, a0 int) (r0 []ProductionCycle, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getByMachineIDMetrics.Begin()
	defer func() { s.getByMachineIDMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "productioncycle.ProductionCycleComponent.GetByMachineID", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += 8
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.Int(a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 2, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_slice_ProductionCycle_ba3c321f(dec)
	err = dec.Error()
	return
}

func (s productionCycleComponent_client_stub) GetFirstCycleByMachineID(ctx context.Context, a0 int) (r0 ProductionCycle, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getFirstCycleByMachineIDMetrics.Begin()
	defer func() { s.getFirstCycleByMachineIDMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "productioncycle.ProductionCycleComponent.GetFirstCycleByMachineID", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += 8
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.Int(a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 3, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	(&r0).WeaverUnmarshal(dec)
	err = dec.Error()
	return
}

// Note that "weaver generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][24]struct{}](`

ERROR: You generated this file with 'weaver generate' v0.24.6 (codegen
version v0.24.0). The generated code is incompatible with the version of the
github.com/ServiceWeaver/weaver module that you're using. The weaver module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/ServiceWeaver/weaver

We recommend updating the weaver module and the 'weaver generate' command by
running the following.

    go get github.com/ServiceWeaver/weaver@latest
    go install github.com/ServiceWeaver/weaver/cmd/weaver@latest

Then, re-run 'weaver generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/ServiceWeaver/weaver/issues.

`)

// Server stub implementations.

type productionCycleComponent_server_stub struct {
	impl    ProductionCycleComponent
	addLoad func(key uint64, load float64)
}

// Check that productionCycleComponent_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*productionCycleComponent_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s productionCycleComponent_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "Add":
		return s.add
	case "Get":
		return s.get
	case "GetByMachineID":
		return s.getByMachineID
	case "GetFirstCycleByMachineID":
		return s.getFirstCycleByMachineID
	default:
		return nil
	}
}

func (s productionCycleComponent_server_stub) add(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 ProductionCycle
	(&a0).WeaverUnmarshal(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.Add(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s productionCycleComponent_server_stub) get(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.Get(ctx)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_slice_ProductionCycle_ba3c321f(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s productionCycleComponent_server_stub) getByMachineID(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 int
	a0 = dec.Int()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetByMachineID(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_slice_ProductionCycle_ba3c321f(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s productionCycleComponent_server_stub) getFirstCycleByMachineID(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 int
	a0 = dec.Int()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetFirstCycleByMachineID(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	(r0).WeaverMarshal(enc)
	enc.Error(appErr)
	return enc.Data(), nil
}

// Reflect stub implementations.

type productionCycleComponent_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that productionCycleComponent_reflect_stub implements the ProductionCycleComponent interface.
var _ ProductionCycleComponent = (*productionCycleComponent_reflect_stub)(nil)

func (s productionCycleComponent_reflect_stub) Add(ctx context.Context, a0 ProductionCycle) (err error) {
	err = s.caller("Add", ctx, []any{a0}, []any{})
	return
}

func (s productionCycleComponent_reflect_stub) Get(ctx context.Context) (r0 []ProductionCycle, err error) {
	err = s.caller("Get", ctx, []any{}, []any{&r0})
	return
}

func (s productionCycleComponent_reflect_stub) GetByMachineID(ctx context.Context, a0 int) (r0 []ProductionCycle, err error) {
	err = s.caller("GetByMachineID", ctx, []any{a0}, []any{&r0})
	return
}

func (s productionCycleComponent_reflect_stub) GetFirstCycleByMachineID(ctx context.Context, a0 int) (r0 ProductionCycle, err error) {
	err = s.caller("GetFirstCycleByMachineID", ctx, []any{a0}, []any{&r0})
	return
}

// AutoMarshal implementations.

var _ codegen.AutoMarshal = (*ProductionCycle)(nil)

type __is_ProductionCycle[T ~struct {
	ProductionCycleID int       "json:\"productionCycleID\""
	MachineID         int       "json:\"machineID\""
	ProductionItem    string    "json:\"productionItem\""
	ProdCount         int       "json:\"prodCount\""
	RejCount          int       "json:\"rejCount\""
	GoodCount         int       "json:\"goodCount\""
	IdealCycleTime    float64   "json:\"idealCycleTime\""
	ProductionTime    float64   "json:\"productionTime\""
	Timestamp         time.Time "json:\"timestamp\""
	weaver.AutoMarshal
}] struct{}

var _ __is_ProductionCycle[ProductionCycle]

func (x *ProductionCycle) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("ProductionCycle.WeaverMarshal: nil receiver"))
	}
	enc.Int(x.ProductionCycleID)
	enc.Int(x.MachineID)
	enc.String(x.ProductionItem)
	enc.Int(x.ProdCount)
	enc.Int(x.RejCount)
	enc.Int(x.GoodCount)
	enc.Float64(x.IdealCycleTime)
	enc.Float64(x.ProductionTime)
	enc.EncodeBinaryMarshaler(&x.Timestamp)
}

func (x *ProductionCycle) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("ProductionCycle.WeaverUnmarshal: nil receiver"))
	}
	x.ProductionCycleID = dec.Int()
	x.MachineID = dec.Int()
	x.ProductionItem = dec.String()
	x.ProdCount = dec.Int()
	x.RejCount = dec.Int()
	x.GoodCount = dec.Int()
	x.IdealCycleTime = dec.Float64()
	x.ProductionTime = dec.Float64()
	dec.DecodeBinaryUnmarshaler(&x.Timestamp)
}

// Encoding/decoding implementations.

func serviceweaver_enc_slice_ProductionCycle_ba3c321f(enc *codegen.Encoder, arg []ProductionCycle) {
	if arg == nil {
		enc.Len(-1)
		return
	}
	enc.Len(len(arg))
	for i := 0; i < len(arg); i++ {
		(arg[i]).WeaverMarshal(enc)
	}
}

func serviceweaver_dec_slice_ProductionCycle_ba3c321f(dec *codegen.Decoder) []ProductionCycle {
	n := dec.Len()
	if n == -1 {
		return nil
	}
	res := make([]ProductionCycle, n)
	for i := 0; i < n; i++ {
		(&res[i]).WeaverUnmarshal(dec)
	}
	return res
}
